version: 2.1
jobs:
  build:
    docker:
      # images at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Setup IS_PRODUCTION environment variable based on version pattern tag."
          command: |
            version_tag_pattern="v[0-9]+(\.[0-9]+)*" # if pushed tag matches pattern
            if [[ $CIRCLE_TAG =~ $version_tag_pattern ]]; then
              export IS_PRODUCTION=true
            else
              export IS_PRODUCTION=false
            fi

            echo "Exporting variables to \"$BASH_ENV\" file, so we can use the variable in other steps as well."
            echo -e "export IS_PRODUCTION=${IS_PRODUCTION}" >> "$BASH_ENV"

            echo "Setting prod context: ${IS_PRODUCTION}"
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm -v
